### ISSUE TITLE
Missing default_config.json in Platform Directory

### ISSUE THREAD

**Issue by JesperBellenbaum** [meta-flutter/workspace_automation#28]
Hi @jwinarske  👋 

The `agl-qemu-octopus.json` and `agl-qemu-master.json` configuration files mention a `default_config.json`, but I can't seem to find it anywhere in the platform directory. Interestingly, I do see a `config.toml` file being created instead. This has me wondering if there's been a recent change that I might have missed.

I'll admit I'm a bit uncertain about how this script is supposed to work overall. It's possible I'm misunderstanding some key aspects of the setup process. Any clarification on the general workflow would be super helpful!

Thanks in advance for any insights you can provide!

**Comment by jwinarske** [comment]
v2.0 introduced config.toml somewhat recently.  The qemu cofigs you are referencing are for reference only, and have not been updated since v1.0.  `emb_cli` will be replacing workspace-automation.

Feel free to post your questions to the Embedded Flutter Discord server; referenced on a number of my repos.
